// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNU1I8IHjIQ7XxoCqxh-2wxqUh6LHzTlI',
    appId: '1:1018602281281:web:3ad91502801eb43fc129c0',
    messagingSenderId: '1018602281281',
    projectId: 'decky-dev',
    authDomain: 'decky-dev.firebaseapp.com',
    storageBucket: 'decky-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhB1ze1FNju4VdNxoeNeW9M2cqVFZq9ZE',
    appId: '1:1018602281281:android:615ff04642199cd8c129c0',
    messagingSenderId: '1018602281281',
    projectId: 'decky-dev',
    storageBucket: 'decky-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_5Yqfol8jxbKJhZJmSO4_Wz_yJTHlyzU',
    appId: '1:1018602281281:ios:027702bc8ac1e7d0c129c0',
    messagingSenderId: '1018602281281',
    projectId: 'decky-dev',
    storageBucket: 'decky-dev.firebasestorage.app',
    iosBundleId: 'jtms.app.decky.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_5Yqfol8jxbKJhZJmSO4_Wz_yJTHlyzU',
    appId: '1:1018602281281:ios:d141e50361d18256c129c0',
    messagingSenderId: '1018602281281',
    projectId: 'decky-dev',
    storageBucket: 'decky-dev.firebasestorage.app',
    iosBundleId: 'com.example.deckyApp',
  );
}
