name: decky_admin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0-333.2.beta

dependencies:
  flutter:
    sdk: flutter
  decky_core:
    path: ../decky_core
  firebase_core: "^4.0.0"
  firebase_auth: "^6.0.1"
  cloud_functions: "^6.0.0"
  cloud_firestore: "^6.0.0"
  firebase_ai: ^3.1.0
  firebase_storage: ^13.0.0
  rxdart: "^0.28.0"
  get_it: ^8.0.3
  go_router: ^14.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
